In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv('Maternal Health Risk Data Set.csv')

In [3]:
df

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]

In [4]:
X = df.drop(['RiskLevel'],axis=1)
y = df.RiskLevel

In [5]:
X

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0      25         130           80  15.0      98.0         86
1      35         140           90  13.0      98.0         70
2      29          90           70   8.0     100.0         80
3      30         140           85   7.0      98.0         70
4      35         120           60   6.1      98.0         76
...   ...         ...          ...   ...       ...        ...
1009   22         120           60  15.0      98.0         80
1010   55         120           90  18.0      98.0         60
1011   35          85           60  19.0      98.0         86
1012   43         120           90  18.0      98.0         70
1013   32         120           65   6.0     101.0         76

[1014 rows x 6 columns]

In [6]:
y

0       high risk
1       high risk
2       high risk
3       high risk
4        low risk
          ...
1009    high risk
1010    high risk
1011    high risk
1012    high risk
1013     mid risk
Name: RiskLevel, Length: 1014, dtype: object

In [7]:
X.BodyTemp = (X.BodyTemp - 32)*5/9

In [8]:
X

      Age  SystolicBP  DiastolicBP    BS   BodyTemp  HeartRate
0      25         130           80  15.0  36.666667         86
1      35         140           90  13.0  36.666667         70
2      29          90           70   8.0  37.777778         80
3      30         140           85   7.0  36.666667         70
4      35         120           60   6.1  36.666667         76
...   ...         ...          ...   ...        ...        ...
1009   22         120           60  15.0  36.666667         80
1010   55         120           90  18.0  36.666667         60
1011   35          85           60  19.0  36.666667         86
1012   43         120           90  18.0  36.666667         70
1013   32         120           65   6.0  38.333333         76

[1014 rows x 6 columns]

In [9]:
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
y

array([0, 0, 0, ..., 0, 0, 2])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [12]:
X_train

     Age  SystolicBP  DiastolicBP    BS   BodyTemp  HeartRate
127   55         140           95  19.0  36.666667         77
491   23         120           90   7.9  36.666667         70
420   60         120           80   6.8  36.666667         77
993   25         120           90  15.0  36.666667         80
995   32         140           90  18.0  36.666667         88
..   ...         ...          ...   ...        ...        ...
579   15         120           80   7.5  36.666667         70
502   63         140           90  15.0  36.666667         90
537   19         120           75   7.5  36.666667         66
196   31         120           60   6.1  36.666667         76
175   21         120           80   7.1  36.666667         77

[811 rows x 6 columns]

In [13]:
X_test

     Age  SystolicBP  DiastolicBP    BS   BodyTemp  HeartRate
113   30         140          100  15.0  36.666667         70
796   23         130           70   6.8  36.666667         78
712   18         120           80   6.9  38.888889         76
510   17          90           63   7.5  38.333333         70
492   29         130           70   7.9  36.666667         78
..   ...         ...          ...   ...        ...        ...
941   60         120           80   7.5  36.666667         75
97    19         120           80   7.0  36.666667         70
807   31         120           60   6.1  36.666667         76
644   25         140          100  15.0  37.000000         70
591   22         120           90   7.5  36.666667         82

[203 rows x 6 columns]

In [14]:
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [15]:
gama = np.arange(0.05, 15, 0.05)
c_vals = np.arange(0.5, 15, 0.5)

In [16]:
# max_acc = 0
# max_gama = 0
# max_c = 0
# for i in gama:
#     for j in c_vals:
#         svm = SVC(kernel='rbf', random_state=7, gamma=i, C=j)
#         svm.fit(X_train, y_train)
#         y_pred = svm.predict(X_test)
#         if accuracy_score(y_test, y_pred) > max_acc:
#             max_acc = accuracy_score(y_test, y_pred)
#             max_gama = i
#             max_c = j

In [17]:
# svm = SVC(kernel='rbf', random_state=7, gamma=max_gama, C=max_c)
# svm.fit(X_train, y_train)
# print('-----------------------')
# print("Train accuracy:",svm.score(X_train,y_train))
# print("Test accuracy:",svm.score(X_test,y_test))
# y_pred = svm.predict(X_test)
# cm = confusion_matrix(y_test, y_pred)
# print('-----------------------')
# print(f"Confusion Matrix:\n {cm}")
# print('-----------------------')
# print(classification_report(y_test, svm.predict(X_test)))

In [18]:
svm = SVC(kernel='rbf', random_state=7, gamma=2.45, C=5.0)
svm.fit(X_train, y_train)

SVC(C=5.0, gamma=2.45, random_state=7)

In [19]:
X_train

     Age  SystolicBP  DiastolicBP    BS   BodyTemp  HeartRate
127   55         140           95  19.0  36.666667         77
491   23         120           90   7.9  36.666667         70
420   60         120           80   6.8  36.666667         77
993   25         120           90  15.0  36.666667         80
995   32         140           90  18.0  36.666667         88
..   ...         ...          ...   ...        ...        ...
579   15         120           80   7.5  36.666667         70
502   63         140           90  15.0  36.666667         90
537   19         120           75   7.5  36.666667         66
196   31         120           60   6.1  36.666667         76
175   21         120           80   7.1  36.666667         77

[811 rows x 6 columns]

In [20]:
svm.predict(X_test)

array([0, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2,
       1, 2, 2, 1, 2, 2, 0, 1, 1, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 1, 0,
       1, 2, 2, 2, 1, 0, 1, 2, 2, 1, 1, 0, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 2, 0, 2, 2, 1, 2, 2, 2, 1, 2, 0,
       0, 2, 2, 1, 0, 0, 2, 2, 0, 1, 2, 2, 1, 1, 1, 1, 0, 2, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 1, 2, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 2, 2, 2, 2, 1,
       0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 1, 2, 2, 0, 1, 1, 2, 0, 2,
       1, 0, 0, 1, 2, 2, 0, 0, 2, 1, 0, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 0, 2, 1, 2, 1, 2, 1,
       2, 2, 2, 1, 2])

In [23]:
svm.score(X_test,y_test)

0.8177339901477833

In [24]:
svm.predict([[22,120,60,15.0,98.0,80]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1])

In [25]:
svm.predict([[-0.51856327,  0.36628779,  0.98629617, -0.24611281, -0.4871202 ,
        -0.58209634]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1])

In [26]:
svm.predict([[25,130,80,15.0,98.0,86]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1])